apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.map.host }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.map.host }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.map.host }}
    spec:
      containers:
        - image: mysql:5.6
          name: {{ .Values.map.host }}
          env:
           - name: MYSQL_ROOT_PASSWORD
             valueFrom:
                configMapKeyRef:
                 name: salvatore-env
                 key: MYSQL_ROOT_PASSWORD
           - name: DATABASE_HOST
             valueFrom:
                configMapKeyRef:
                 name: salvatore-env
                 key: DATABASE_HOST
          ports:
            - containerPort: 3306
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
